@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Samuel Silva",
    "email": "samuel3@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "samuel3@gmail.com",
    "password": "123456"
}

###

# @name create_goal
POST {{baseUrl}}/goals
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Meta de Teste 3",
    "targetAmount": 1000.00,
    "currentAmount": 0.00,
    "deadline": "2024-12-31T23:59:59Z"
}

###

# @name get_goals
GET {{baseUrl}}/goals
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_transaction
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "description": "Salário do mês",
    "amount": 5000.00,
    "date": "2026-03-29T10:00:00Z",
    "type": "INCOME",
    "categoryName": "Salário",
    "source": "Trabalho"
}

###

# @name fetch_expenses
GET {{baseUrl}}/transactions?type=EXPENSE&page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_income
GET {{baseUrl}}/transactions?type=INCOME&page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_categories
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}