@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Samuel Silva",
    "email": "teste@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "samuel@gmail.com",
    "password": "123456"
}

###

# @name create_goal
POST {{baseUrl}}/goals
Content-Type: application/json
Authorization: Bearer {{authToken}}
